name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # Specify the path to package-lock.json for caching
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    # Commands to run in the frontend directory
    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build
      run: npm run build --if-present
      working-directory: ./frontend

    - name: Run tests
      run: npm test
      working-directory: ./frontend
